#ifndef _PROGS_H
#define _PROGS_H

#include <stdio.h>
/*#include "display.h"*/
#include "vt52.h"

extern void progs_bottom_title( void );
extern void progs_bottom_title( void);
extern void auto_window( void );
extern void progs_up_arrow( void );
extern void progs_down_arrow( void );
extern void progs_right_arrow( void );
extern void progs_left_arrow( void );
extern void print_auto_title( int );
extern void progs_paging( void );
extern void progs_paging_up( void );
extern int progs_main_loop( int * );


#endif





